[project]
name = "can"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "canopen>=2.4.1",
    "matplotlib>=3.10.7",
    "python-can>=4.6.1",
]
